### ISSUE TITLE
Projects and Ideas to start 

### ISSUE THREAD

**Issue by ypriverol** [BigDataProteomics/bigdataproteomics.github.io#1]
Here we will define the set of projects we can start with advantages and disadvantages. I think three ideas are poor discussed in the literature and current analysis:
  - Spectral Search.
  - De novo Sequence.
  - Blind PTM.

**Comment by ypriverol** [comment]
- **Spectral Library Search Pipeline**: Different spectral search algorithms has been developed and use 
  recently. The most widely used is the SpectraST with more than 100 citations. Here some 
  documentation for it: 
    Source code: http://sourceforge.net/p/sashimi/code/HEAD/tree/branches/TPP5-Refactor/trans_proteomic_pipeline/src/Search/SpectraST/
     Original Documentation: http://tools.proteomecenter.org/wiki/index.php?title=Software:SpectraST

  **Only one dataset is public in PRIDE Archive using spectraST. Major problems I see:**
     - Lot of parameters to run an experiment, see documentation. 
     - Incomplete spectral libraries.
     - Low integration with other tools (quantitation, database search, **protein inference**, etc)
     - It can be use only in the context of TPP. 
     - Libraries are huge files (GBs), needs to be download separately and most of the users are more 
       familiar with download one simple file from uniprot and index it. 

   **Opportunities:**
     - Open Spectral Search to identified:
                 (PTMs, Species, Precursor and Fragment tolerances). 
     -

**Comment by ypriverol** [comment]
- **De novo Pipeline:** Different de novo algorithms has been used in recent years, the best option is 
     PEAKS, but some interesting options also are:
    - UniNovo: http://proteomics.ucsd.edu/Software/UniNovo/
    - PepNovo or PepNovo+: http://proteomics.ucsd.edu/Software/PepNovo/
  Both algorithms were developed in the same team.

**Comment by ruiwanguk** [comment]
Nice notes on de-novo pipeline. May be I am wrong, I thought that PEAKS de-novo pipeline is only suitable for certain types of fragmentation techniques, whereas, UniNovo claims that it can be applied to all fragmentation techniques.

**Comment by ypriverol** [comment]
The other problem is that PEAKS is commercial and Uninovo is open-source, then we can start with Uninovo in any case.

**Comment by ypriverol** [comment]
With these three ideas in mind we can start with the Spectral Search Approach. Let me know if you are agree to open an issue only for it. Three things are important here from my point of view:
  - We have more experience with that as search strategy. (both you and me).
  - We can reuse most of our code and ideas. (you and me).
  - We can move to other topics like spectral search, SWATH, Identification, decoy generation, Protein 
    inference in top of search.
**Main disadvantages, overlapping with other PRIDE Projects.**
@ruiwanguk  Let me know your opinion.

**Comment by ruiwanguk** [comment]
My main concerns is that doing spectral search will be, as you said, overlapping with other PRIDE projects. Johannes is doing a lot of spectral search related research and using different libraries; he will not be pleased to find out about our project. I would prefer to avoid this if possible. 

On the other hand, since Johannes is doing a lot of his research on this subject. It would be better if we can benefit from his results, it would be better, in my opinion, wait a bit until he have more results. 

My original plan for starting this project is to start working on deno sequencing, mainly because this will be a green field project, and a nice problem to solve for the community.

**Comment by ypriverol** [comment]
@ruiwanguk Agree with you and it was my main concern at the very beginning with the Spectra search. My main concern with de novo sequence is that de novo generate a lot of possibilities and matches. Even if is a great tool and strategy, it should be combine with other strategies to decrease the number of possibilities. As I mentioned before in case of PEAKS they started using de novo sequencing and now they are combining the identifications with the database-search. From my point of view de-novo sequencing open a great possibility for:
   - To detect new PTMs.
   - New sequence variants (AA mutations, sequences, etc)
   - Validate the identifications, etc. 
The de novo sequencing is the desired algorithm for cloud for many reasons, because is consuming, because is based on alignments, because can be benefit a lot from Machine Learning, because it is a **Graph based algorithms**. My main concern is that we can produce something great but the out-put will be difficult to plug in-side a lab-pipeline. At the same time, it would be the bigger challenge in term of algorithms and future proteomics algorithm.

**Comment by ypriverol** [comment]
@ruiwanguk really important here is that the ongoing project with Brasil (the grant I wrote) is about de novo identification.

**Comment by ypriverol** [comment]
We already decided to start from de novo project but taking into account the possibility to integrate other strategies in the future. I will close the issue.

**Comment by ypriverol** [comment]
Done
