### ISSUE TITLE
Open Source Licence

### ISSUE THREAD

**Issue by ruiwanguk** [BigDataProteomics/bigdataproteomics.github.io#11]
We need to decide an open source software license for other to use and contribute to our software. I would vote for Apache 2 open source licence, but open for suggestions.

**Comment by ypriverol** [comment]
Agree!!

**Comment by ruiwanguk** [comment]
Actually, how about [Contributor Licence Agreements](http://oss-watch.ac.uk/resources/cla)

**Comment by ruiwanguk** [comment]
This will help us to reserve some rights about the project for the future.

**Comment by ypriverol** [comment]
I don't have to mush experience with licences. From my point of view we should take the one that allow us to have contributions from outside and also fork the code and extend it.

**Comment by ruiwanguk** [comment]
Let's go for Apache 2, it is easier for people to understand and contribute.
