### ISSUE TITLE
Reconsider Project Name

### ISSUE THREAD

**Issue by ruiwanguk** [BigDataProteomics/bigdataproteomics.github.io#13]
@ypriverol I knew we discussed this before. But may be we should reconsider our project name, a more original name for proteomics. 

Considering that we are going to apply the Amazon Education Grant, it would be better to have a more proteomics related name that does not reminder people of big data genomics.

**Comment by ruiwanguk** [comment]
A few names to consider:

- Mass Proteomics (MP)
- Mass Scale Proteomics (MSP)
- Mass Proteomics Platform (MPP)
- Super Throughput Proteomics (STP)
- InterProteomics
- Proteomics Stack

**Comment by ypriverol** [comment]
Agree with you, I think about Future Computational Proteomics (FCP) or Future Proteomics. I like this ideas because always is future ;) We can put all of them and see how they works and what is the best option.

**Comment by ruiwanguk** [comment]
Some more:
- Computational Proteomics Stack (CPS)
- Proteomics Bundle or ProteoBundle
- ProteoMesh
- ProteoFuse

**Comment by ruiwanguk** [comment]
I like the fun aspect of the FCP, but we want to push this into production in the future, don't we?

**Comment by ypriverol** [comment]
Yes, But FCP guaranty that we will be always in the future, even if we change the technology, software.

**Comment by ruiwanguk** [comment]
Ok, I can see that you really like this name. How about we wait a bit and make a decision next week?

**Comment by ypriverol** [comment]
Sure, We can basically discuss of the option next week and come with a final solution. I will look for the other if some projects exist with those name.

**Comment by ruiwanguk** [comment]
Some other ideas:

- Parallel Computational Proteomics
- Parallel Proteomics Stack

**Comment by ypriverol** [comment]
@ruiwanguk I will put all the options here:
 
 - Mass Proteomics (MP)
 - Mass Scale Proteomics (MSP)
 - Mass Proteomics Platform (MPP)
 - Super Throughput Proteomics (STP)
 - InterProteomics (IP)
 - InterSpectromics (IS)
 - Proteomics Stack (ProteoStack)
 - mzStack
 - Future Computational Proteomics (FCP)
 - Computational Proteomics Stack (CPS)
 - Proteomics Bundle or ProteoBundle
 - ProteoMesh
 - ProteoFuse 
 - Mass Proteomics Solution (MPS)
 - ProteoBytes
 - Parallel Computational Proteomics (PCP)
 - Parallel Proteomics Stack  (PPS)
 - High Performance Computational Proteomics (HPCP)
 - Large Scale Computational Proteomics (LSCP)

**Comment by ruiwanguk** [comment]
Can we decide on the name today?

**Comment by ypriverol** [comment]
Yes.. in order to advance .. I will spend some time to see which one are already take it before in other projects or mentioned in some way.

**Comment by ypriverol** [comment]
Scalable Proteomics Stack is the final option!
