### ISSUE TITLE
Based funcionalities and libraries to be used or developed

### ISSUE THREAD

**Issue by ypriverol** [BigDataProteomics/bigdataproteomics.github.io#3]
@ruiwanguk From y point of view any CP platforms needs some basic functionalities or libraries to work. Before anything we should define the PTMs representation and Enzyme. It would be great to define this issues before anything. The things than needs to be standardise are:
    - **Modifications**: My guest is UNIMOD representation.
    - **Enzyme**: We can develop a based class with the most important ones using perhaps the CVterms
                           for that.

**Comment by ruiwanguk** [comment]
I agree with you that we need to a core set of objects which will be shared across the projects. This will avoid the problem we are having with PRIDE right now. 

I would also suggest we have some documentation explain each of these concept on what we mean. Also, it would be nice to have the following objects. 

**Spectrum**
**PSM**
**Peptide**

These objects we have already defined in PRIDE Cluster project, may be we can review these classes, then add them accordingly.

**Comment by ruiwanguk** [comment]
I have created an repo call proteomics-core, for maintaining a core set of classes for all our projects. 

The idea of this core is only to contain Plain Old Objects on key concepts of proteomics. Utility classes or other business logics should not be included in here. 

Would you agree?

**Comment by ypriverol** [comment]
@ruiwanguk Agree, but also think in other project with general approach, for example PSM in the context of PRIDE cluster can be only the Sequence + modification + charge state, but in the context of Database search can also include protein accession. I was reading the ADAM format from Big Data Genomics and this was the first step, they used Spark Apache avro and parquet and define using json schemas all the entities, etc. 
My main idea is before core-objects is more related with modifications that we will use, Enzyme, taxonomy annotations, etc. 
Example: Users want to run from command line a search using the tool and want to define a set of modifications to be searched, we need to provide them as search parameters and the data in the libraries should contain the proper annotations to be fully useful. Actually it would be interesting to see in the context of PRIDE libraries how we will do it. 
Any project start with that, which are the reference notations they will use and keep them homogenues in the project to avoid future problems of mapping etc.

**Comment by ruiwanguk** [comment]
I would also suggest that we have a core set of interfaces and providing one implementation for each interface. 

For example for spectrum, we can have:

- *ISpectrum* as the interface
- *Spectrum* as the implementation

**Comment by ypriverol** [comment]
Complete Agree with this suggestion. We can reuse our classes from previous PRIDE Projects. Remember we should think about quantitation for the future, them we should consider MS1 and MS2 as representation.

**Comment by ruiwanguk** [comment]
Yasset, I see your point on variation of the objects, particular for PSM's. There is a nice way of implementing additional properties or features. 

For example, we can make use of properties in Java, where treat each feature as a additional property to the object. This way we will have flexibility on how many properties we would like to include.

**Comment by ypriverol** [comment]
For modifications, I prefer to use UNIMOD modification database as the reference database. Main reasons for this suggestion: 
    - Maintained by a Commercial software.
    - already use by other peace of softwares, contain the most common modification. 
For unknown modifications we can use the CHEMOD notations, where you put the mass difference like:
  CHEMOD:+57

**Comment by ruiwanguk** [comment]
Agree with using UniMoD

**Comment by ypriverol** [comment]
for example if we found a modification in the PRIDE libraries with PSI-Mod and is not included in the Unimod then we should use CHEMOD:mass difference and that's it. Agree?

**Comment by ruiwanguk** [comment]
Agree! What about Enzyme? Which ontology is better?

**Comment by ypriverol** [comment]
PSI-MS can be use for that, I'm just thinking http://www.ebi.ac.uk/ontology-lookup/browse.do?ontName=MS&termId=MS:1001044&termName=cleavage%20agent%20details .. I want to make this "Standard compliant" for future developments and integration with other tools and peace of code we normally develop in PRIDE or other tools

**Comment by ypriverol** [comment]
For that we can create an utility class to map the most important objects, because we don't want to over complicate the annotation process it can be a simple class like we did for PRIDE Utilities or a simple file which all the terms we are using.

**Comment by ruiwanguk** [comment]
How about this instead? 

http://www.ebi.ac.uk/ontology-lookup/browse.do?ontName=MS&termId=MS:1001045&termName=cleavage%20agent%20name

**Comment by ypriverol** [comment]
@ruiwanguk Agree. Do you think is better to keep a class with all the mapping (PRIDE Utilities approach), or file oriented approach were you put the term in use. The second approach can be better to extend because you can only add terms without need to change the code.

**Comment by ruiwanguk** [comment]
I like the idea of keep this flexible. For the file oriented approach, I would prefer not to get into any XML related crab, may be keep it simple to just use TSV file.

**Comment by ypriverol** [comment]
Agree to move out of XML things, TSV is fine for me. I don't know if is an stupid idea but i like to do some research about json-based representations. Imagine someone wants to share this file in the web or do some kind of visualization...?

**Comment by ypriverol** [comment]
First model classes to be implemented from my point of view are the ones related with Spectrum handling, it would be interesting to take into consideration future improvements like SAWTH representation, retention time, relation between spectrum like MS1->MS2, alignment between spectrum, etc.

**Comment by ypriverol** [comment]
I will close this issue and open to issues in the bdp-core and bdp-utils related with it.
