### ISSUE TITLE
package structure for the project

### ISSUE THREAD

**Issue by ruiwanguk** [BigDataProteomics/bigdataproteomics.github.io#4]
Going forward, I suggest that we agree on a package structure for all our projects. 

Here are some ideas:

- uk.ac.ebi.bigdataproteomics
- uk.ac.ebi.bdp
- org.bigdataproteomics
- org.bdp

I personally prefer not to include pride in the package name to give us some flexibility for the future.

**Comment by ypriverol** [comment]
I prefer to go for the last option, as far as i understand and see short notations are better for everything, sharing, urls, etc. Also put the ebi name in something is not really the ideas of the ebi can be risky if we fail becuase then we put the EBI name in a bad and not sussesful idea... 
**100% with org.bgp**

**Comment by ypriverol** [comment]
If you are agree we can close this issue and it would be the first BDP closed issue.
