### ISSUE TITLE
Mission Statement for Big Data Proteomics project

### ISSUE THREAD

**Issue by ruiwanguk** [BigDataProteomics/bigdataproteomics.github.io#5]
1. Provide high throughput proteomics data analysis pipelines.
2. These pipelines need to be able to scale with the future data growth.
3. These pipelines should be reusable for the proteomics community.

**Comment by ypriverol** [comment]
The mission and statement of **Big Data Proteomics** is to design and implement a platform for fast and accurate analyses of proteomics data on top of high performance distributed computing frameworks.

1. Provide high throughput proteomics data analysis pipelines.
2. These pipelines need to be able to scale with the future data growth.
3. These pipelines should be reusable for the proteomics community.

**Comment by ypriverol** [comment]
@ruiwanguk I think we can include an option related with providing the data, for example if we release a database in the future or file format for spark representation of the proteomics data is not included in any of the previous statements:

4. Databases, formats for fast access to the data.

**Comment by ypriverol** [comment]
The mission and statement of Big Data Proteomics is to design and implement a platform for fast and accurate analyses of proteomics data on top of high performance distributed computing frameworks.

1. Provide high throughput proteomics data analysis pipelines.
2. These pipelines need to be able to scale with the future data growth.
3. These pipelines should be reusable for the proteomics community.
4. Provide databases, formats for fast access to final results.

**Comment by ruiwanguk** [comment]
Yasset, I agree on publishing file formats for the community. However, I am not sure about including databases into our mission statement, they will not be directly related to our pipelines assuming you are talking about loading the output into a data store. In my opinion, this should be left out.

**Comment by ypriverol** [comment]
The mission and statement of Big Data Proteomics is to design and implement a platform for fast and accurate analyses of proteomics data on top of high performance distributed computing frameworks.

1. Provide high throughput proteomics data analysis pipelines.
2. These pipelines need to be able to scale with the future data growth.
3. These pipelines should be reusable for the proteomics community.
4. Formats for fast access to final results.

**Comment by ypriverol** [comment]
@ruiwanguk if yo are agree we can close the issue.

**Comment by ruiwanguk** [comment]
Yes, I am happy to close this issue.
