### ISSUE TITLE
Spark data and files 

### ISSUE THREAD

**Issue by ypriverol** [BigDataProteomics/bigdataproteomics.github.io#9]
@ruiwanguk One of the great things with Spark is to have the data in a local place "spark cluster" to avoid file transfer. If we think to implement this in the future, how we can keep data in the Spark Cluster.

**Comment by ruiwanguk** [comment]
Spark is primarily using the HDFS which is the native file system for Hadoop. I would suggest that we use the default for now, HDFS is good for general purpose storage with build-in fault tolerance. 

Although file systems such as: relational databases, S3, and Cassandra are supported, I think these are for the future.

**Comment by ypriverol** [comment]
Ok
